version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: eHH
      MYSQL_USER: ehh_user
      MYSQL_PASSWORD: ehh_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ehh-net

volumes:
  db_data:

networks:
  ehh-net:
