version: '3'
services:
  dns:
    build: ./bind
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      - ehh-net

  web:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - ehh-net

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: eHH
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - ehh-net

  ftp:
    build: ./vsftpd
    ports:
      - "20:20"
      - "21:21"
    networks:
      - ehh-net

  mail:
    image: tvial/docker-mailserver
    environment:
      MAIL_USER: admin
      MAIL_PASS: password
    ports:
      - "25:25"
      - "143:143"
    networks:
      - ehh-net

networks:
  ehh-net:

volumes:
  db-data:
