services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"

  mail:
    image: mailserver/docker-mailserver:latest
    hostname: mail
    domainname: eHH.de
    container_name: mailserver
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./maildata/:/var/mail/
      - ./mailstate/:/var/mail-state/
      - ./config/:/tmp/docker-mailserver/
      - ./postfix-spool:/var/spool/postfix
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ONE_DIR=1
      - DMS_DEBUG=0
    cap_add:
      - NET_ADMIN
    networks:
      - ehh-net

  web:
    build: ./nginx
    container_name: webserver
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - ehh-net

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: eHH
      MYSQL_USER: ehh_user
      MYSQL_PASSWORD: ehh_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ehh-net
  
  ftp:
    build: ./vsftpd
    container_name: ftp-server
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - ehh-net

volumes:
  db_data:

networks:
  ehh-net: