global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9090', 'localhost:80', 'localhost:143', 'localhost:21']  # Add additional targets as needed
